[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qsim"
version = "1.0.0"
description = "Quantum simulator module for open and closed system dynamics"
authors = [{name="Matthew Mackinnon"}]
dependencies = [
    "numpy>=1.24",
    "scipy>=1.10",
    "tqdm>=4.67"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
