from __future__ import annotations

from typing import Protocol, TypeVar

R = TypeVar("R")


class QuantumState(Protocol):

    def __matmul__(self, other: QuantumState) -> QuantumState: ...
    def __rmatmul__(self, other: QuantumState) -> QuantumState: ...
    def normalise(self) -> QuantumState: ...
    def accept(self, visitor: StateVisitor[R], **kwargs) -> R: ...
    @property
    def dim(self) -> int: ...


class StateVisitor(Protocol[R]):

    def visitKet(self, psi: "Ket", **kwargs) -> R: ...
    def visitBra(self, psi: "Bra", **kwargs) -> R: ...
    def visitDensityMatrix(self, rho: "DensityMatrix", **kwargs) -> R: ...
